#!/usr/bin/env bash
#
# Summary: Prints completion options for a command
#
# Usage: luav comp <command> [<args>]
#

if [[ $# -ge 1 ]]
then
	command=$1
	shift
else
	usage
fi

if [[ $# -eq 0 ]]
then
	case "$command" in
	get )
		libexec/all
		;;
	set | unset | make | rm )
		libexec/list
		;;
	help | comp )
		libexec/cmds
		;;
	esac
elif [[ $# -eq 1 ]]
then
	case "$command" in
	make )
		if libexec/list | grep -q "^$1$"
		then
			awk -F ':' '/^[a-z-]+:/ { print $1 }' versions/$1/Makefile versions/$1/src/Makefile
		fi
		;;
	esac	
fi
