#!/usr/bin/env bash
#
# Summary: Prints completion options for a command
#
# Usage: luav comp <command> [<args...>]
#

if [[ $# -ge 1 ]]
then
	command=$1
	shift
else
	usage
fi

if [[ $# -eq 0 ]]
then
	case "$command" in
	get )
		libexec/all
		;;
	set | unset | make | rm | tgts )
		libexec/list
		;;
	help | comp )
		libexec/cmds
		;;
	esac
elif [[ $# -eq 1 ]]
then
	case "$command" in
	make )
		if libexec/list | grep -q "^$1$"
		then
			libexec/tgts "$1"
		fi
		;;
	esac	
fi
