#!/usr/bin/env bash
# 
# Summary: Browse through the manual of a version of Lua
#
# Usage: luav doc <version>
#
# Hint: You can select other browser by setting the BROWSER environment variable
# Hint: The default browser is firefox, found in most GNU/Linux distros
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

manual=versions/$version/doc/manual.html

if [[ -f $manual ]]
then
	${BROWSER:-firefox} "$manual"
else
	echo "Version $version does not contain manual" >&2
	exit 1
fi
