#!/usr/bin/env bash
#
# Summary: Download a specific version of Lua
#
# Usage: luaver get <version>
#

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	usage
fi

mkdir -p versions
curl -s "http://www.lua.org/ftp/lua-$version.tar.gz" | tar xz --transform='s/^lua-//'
sed 's/^CFLAGS.*/\0 \$(LUAVERCFLAGS)/' -i "versions/$version/src/Makefile"
