#!/usr/bin/env bash
#
# Summary: Download an indexed version of Lua
#
# Usage: luav get <version>
#

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	usage
fi

mkdir -p versions

if ! hasversion "$version"
then
	echo "Version '$version' not available" >&2
	echo "Hint: luav update" >&2
	exit 1
fi

file=lua-$version.tar.gz
curl -s -R -O "https://www.lua.org/ftp/$file"

if command -v sha256sum > /dev/null
then
	libexec/info | awk -v "FILE=$file" '$1 == FILE { print $2, $1 }' | sha256sum -c --quiet
else
	echo "Error: Cannot check SHA-256 digest of file because program 'sha256sum' is missing" >&2
	exit 1
fi

tmpdir=$(mktemp -d)
tar zxf "$file" -C "$tmpdir"
rm -rf "versions/$version"
mv "$tmpdir/$(ls -1 "$tmpdir")" "versions/$version"
rm -rf "$tmpdir" "$file"

grep '^CFLAGS=' -r "versions/$version" -l -I | \
	xargs sed 's/^CFLAGS=.*/\0 \$(LUAVCFLAGS)/' -i
