#!/usr/bin/env bash
#
# Summary: Download a specific version of Lua
#
# Usage: luav get <version>
#

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	usage
fi

mkdir -p versions

hasversion() { libexec/all | grep -q "$1" ; }

if ! hasversion "$version"
then
	libexec/update
	if ! hasversion "$version"
	then
		echo "Version '$version' not found." 2>&1
		exit 1
	fi
fi

file=lua-$version.tar.gz
curl -s -R -O "http://www.lua.org/ftp/$file"

if command -v md5sum > /dev/null
then
	libexec/info | awk -v "FILE=$file" '$1 == FILE { print $3, $1 }' | md5sum -c --quiet
fi

if command -v sha1sum > /dev/null
then
	libexec/info | awk -v "FILE=$file" '$1 == FILE { print $2, $1 }' | sha1sum -c --quiet
fi

tmpdir=$(mktemp -d)
tar zxf "$file" -C "$tmpdir"
rm -rf "versions/$version"
mv "$tmpdir/$(ls -1 "$tmpdir")" "versions/$version"
rm -rf "$tmpdir" "$file"
sed 's/^CFLAGS.*/\0 \$(LUAVCFLAGS)/' -i "versions/$version/src/Makefile"
