#!/usr/bin/env bash
#
# Summary: Prints information about commands
#
# Usage: luav help [<command>]
#

if [[ $# -ge 1 ]]
then
	command=$1
	shift

	if [[ ! -f libexec/$command ]]
	then
		echo "Command '$command' doesn't exist" 2>&1
		exit 1
	fi

	awk -f libexec/awk/help.awk "libexec/$command"
else
	echo "Usage: luav <command> [<args>]"
	echo "       luav help <command>"
	echo "       luav help"
	echo ""
	echo "Available commands:"

	maxcmdlength=$(find libexec -maxdepth 1 -type f -regex 'libexec/[a-z-]*' | xargs -n1 basename | wc -L)

	for cmdfile in $(find libexec -maxdepth 1 -type f -regex 'libexec/[a-z-]*' | sort)
	do
		printf "  %${maxcmdlength}s  %s\n" "$(basename "$cmdfile")" "$(sed -ne 's/^# Summary: // p' "$cmdfile")"
	done
fi
