#!/usr/bin/env bash
#
# Summary: Prints luav initialization code
#
# Usage: eval "$(luav init)"
#

shell=$(ps -hp $$ | awk '{print $5}')
shellfile=libexec/completions/luav.$shell

if [[ -f $shellfile ]]
then
	echo "source \"$PWD/$shellfile\""
else
	echo "echo \"luav: found no completion for '$shell' shell\" 2>&1"
fi
