#!/usr/bin/env bash
# 
# Summary: Run make for a version of Lua
#
# Usage: luav make <version> [<options...>]
#
# Hint: You can set compiler flags through the CFLAGS environment variable
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

LUAVCFLAGS="$CFLAGS" make -C "versions/$version" "$@"
