#!/usr/bin/env bash
# 
# Summary: Run make for a specific version of Lua
#
# Usage: luaver make <version> [<targets-and-flags>]
#
# Hint: You can customize your compilation by setting the CFLAGS environment variable
#

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	usage
fi

if [[ ! -d versions/$version ]]
then
	echo "Version $version not found" 2>&1
	echo "Hint: luaver get $version" 2>&1
	exit 1
fi

LUAVERCFLAGS="$CFLAGS" make -C "versions/$version" "$@" -s
