#!/usr/bin/env bash
# 
# Summary: Make targets for a specific version of Lua
#
# Usage: luaver make [<targets>]

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	echo "Usage: luaver make <version>" 2>&1
	exit 1
fi

if [[ ! -d versions/lua-$version ]]
then
	echo "Version $version not found" 2>&1
	echo "Hint: luaver get $version" 2>&1
	exit 1
fi

make -C "versions/lua-$version" "$@"
