#!/usr/bin/env bash
# 
# Summary: Remove a local version of Lua
#
# Usage: luav rm <version>
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

rm -rf "versions/$version"
