#!/usr/bin/env bash
# 
# Summary: Remove Lua version
#
# Usage: luav rm <version>
#

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	usage
fi

if [[ ! -d versions/$version ]]
then
	echo "Version '$version' not found" 2>&1
	echo "Hint: luav get $version" 2>&1
	exit 1
fi

rm -rf "versions/$version"
