#!/usr/bin/env bash
# 
# Summary: Set a Lua version as default
#
# Usage: luav set <version>
#
# Hint: You can select other 'super user do' program by setting the SUDO environment variable
# Hint: This defaults to sudo, found in most GNU/Linux distros
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

${SUDO:-sudo} make -C "versions/$version" install -s
