#!/usr/bin/env bash
# 
# Summary: Set a Lua version as default
#
# Usage: luav set <version>
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

sudo make -C "versions/$version" install -s
