#!/usr/bin/env bash
#
# Summary: Run unit tests for luav commands
#
# Usage: luav test [<commands...>]
#
# Note: If <commands...> is missing, all commands will be tested
# Note: This might mess with your local versions
#

source tests/framework

BEGIN_TEST

export version=5.4.2

if ! bin/luav list | grep -qF "$version"
then
	T 'bin/luav get $version'
fi

export notversion=1.0

if bin/luav list | grep -qF "$notversion"
then
	T 'bin/luav rm $notversion'
fi

if [[ $# -eq 0 ]]
then
	commands=$(libexec/cmds)
else
	commands="$@"
fi

for cmd in $commands
do
	if ! libexec/cmds | grep -qF "$cmd"
	then
		echo "Command '$cmd' does not exist" 2>&1
		END_TEST
		exit 1
	fi

	if [[ ! -f tests/$cmd ]]
	then
		echo "Test for command '$cmd' is missing" 2>&1
		continue
	fi

	T "tests/$cmd"
done

END_TEST
