#!/usr/bin/env bash
#
# Summary: List all main targets of a version of Lua
#
# Usage: luav tgts <version>
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

find "versions/$version" -name Makefile -type f | xargs awk -F: '/^[a-z-]+:/ { print $1 }' 
