#!/usr/bin/env bash
#
# Summary: Lists all main targets of a specific version of Lua
#
# Usage: luav tgts <version>
#

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	usage
fi

if [[ ! -d versions/$version ]]
then
	echo "Version '$version' not found" 2>&1
	echo "Hint: luav get $version" 2>&1
	exit 1
fi

find "versions/$version" -name Makefile -type f | xargs awk -F: '/^[a-z-]+:/ { print $1 }' 
