#!/usr/bin/env bash
# 
# Summary: Unset Lua version as default
#
# Usage: luaver unset <version>
#
# Hint: Some older versions of Lua don't support this feature
#

if [[ $# -ge 1 ]]
then
	version=$1
	shift
else
	usage
fi

if [[ ! -d versions/$version ]]
then
	echo "Version $version not found" 2>&1
	echo "Hint: luaver get $version" 2>&1
	exit 1
fi

sudo make -C "versions/$version" uninstall
