#!/usr/bin/env bash
# 
# Summary: Unset a Lua version as default
#
# Usage: luav unset <version>
#
# Hint: Some older versions of Lua don't support this feature
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

sudo make -C "versions/$version" uninstall -s
