#!/usr/bin/env bash
# 
# Summary: Unset a Lua version as default
#
# Usage: luav unset <version>
#
# Hint: Some older versions of Lua don't support this feature
# Hint: You can select other 'super user do' program by setting the SUDO environment variable
# Hint: This defaults to sudo, found in most GNU/Linux distros
#

if [[ $# -ge 1 ]]
then
	checklocalversion "$1"
	version=$1
	shift
else
	usage
fi

${SUDO:-sudo} make -C "versions/$version" uninstall -s
